<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * @file
 * Integration with brugbyen.kk.dk
 */

/**
 * Implements hook_form_alter().
 */
function kdb_brugbyen_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  if (!in_array($form_id, ['eventseries_default_add_form', 'eventseries_default_edit_form'])) {
    return;
  }

  $form['#validate'][] = 'kdb_brugbyen_eventseries_default_validate';

  // Only activate the secondary categories, target groups and tags elements
  // when district is non-empty.
  $districtIsEmpty = [':input[name="field_bb_district"]' => ['value' => '']];
  $form['field_bb_categories']['#states'] = [
    'disabled' => $districtIsEmpty,
    // Setting required would be nice, but apparently that doesn't work with
    // Select2 and/or field widgets.
  ];

  $form['field_bb_target_groups']['#states'] = [
    'disabled' => $districtIsEmpty,
  ];

  $form['field_bb_tags']['#states'] = [
    'disabled' => $districtIsEmpty,
  ];
}

/**
 * Validate handler for brugbyen data.
 *
 * Validates that categories and target_groups are provided when a district is
 * selected.
 */
function kdb_brugbyen_eventseries_default_validate(array &$form, FormStateInterface $form_state) {
  if (!empty($form_state->getValue('field_bb_district'))) {
    if (empty($form_state->getValue('field_bb_categories'))) {
      $form_state->setError(
        $form['field_bb_categories']['widget'],
        t('@name field is required.', [
          '@name' => $form['field_bb_categories']['widget']['#title'],
        ]),
      );
    }

    if (empty($form_state->getValue('field_bb_target_groups'))) {
      $form_state->setError(
        $form['field_bb_target_groups']['widget'],
        t('@name field is required.', [
          '@name' => $form['field_bb_target_groups']['widget']['#title'],
        ]),
      );
    }
  }
}
